version: '3.7'

services:
  auth:
    container_name: todo-list-auth
    image: node:14-slim
    volumes:
      - ./auth:/src
    working_dir: /src
    command: node server.js
    ports:
      - 3000:3000
  postgres:
    container_name: todo-list-db
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/ddl:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin-user
      POSTGRES_PASSWORD: admin-pass
      POSTGRES_DB: reactivetodo
