spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:local}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.r2dbc.R2dbcDataAutoConfiguration,org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
